apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: web
spec:
  {{- if eq .Values.ingressClassName "web-app-routing" }}
  ingressClassName: webapprouting.kubernetes.azure.com
  {{- else if eq .Values.ingressClassName "nginx" }}
  ingressClassName: nginx
  {{- end }}
  tls:
    - hosts:
        - {{ .Values.domain_name }}
      secretName: cert-tls
  rules:
    - host: "{{ .Values.domain_name }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-service
                port:
                  number: 8080